version: "3.7"
services:

  account-api:
    build:
      context: account-api
      dockerfile: buildimg.Dockerfile
    volumes:
      - ./account-api/code:/var/www/html

  hcontrol-mongo:
    volumes:
    - ./mongodb/init-mongo.sh/docker-entrypoint-initdb.d/init-mongo.sh

