version: "3.7"
services:

  account-api:
    build:
      context: account-api
      dockerfile: Dockerfile
    volumes:
    - ./account-api/code:/var/www/html

  hcontrol-mongo:
    ports:
      - "27017:27017"

  hcontrol-mysql:
    volumes:
      - hcontrol-mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:

  hcontrol-mysql-volume:
    driver: local
